### ISSUE TITLE
Can't use my own Namespace

### ISSUE THREAD

**Issue by ifew** [zaccharles/lambda-native#1]
Hi,

I very love this code, it makes my Lambda is faster 
for try example very easy to learning but so difficult via Nuget because document not clear
and then I found issues when we change the namespace to another, not use "LambdaNative"

Thank for developing it

ps. sorry for bad english

**Comment by zaccharles** [comment]
Hi @ifew 

You will probably need to change `rd.xml` when you change the namespace: https://github.com/zaccharles/lambda-native/blob/master/example/rd.xml#L4

On a related topic, the CoreRT project has an issue tracking change related to `rd.xml` here: https://github.com/dotnet/corert/issues/5001

**Comment by ifew** [comment]
Hi @zaccharles 

I try to fix my code and root causes by missing using namespace T-T

now I completed my example via net core 2.2, and it can work!
but I don't know my practice are correct or not. because I'm not using rd.xml

You can see on https://github.com/ifew/aws-lambda-lambdanative 

Thank you
