### ISSUE TITLE
Can't open connection for MySqlConnection()

### ISSUE THREAD

**Issue by ifew** [zaccharles/lambda-native#3]
I using Dapper instead EFCore and it's very faster and then I convert to LambdaNative and its have a problem.

I debugging line by line and I found some method/properties of MySqlConnection can't use such as

- _connection.State
- _connection.Open();

and I got error message

```bash
START RequestId: 45396de3-dda5-4ab9-9774-65d0b4a9a22b Version: $LATEST
END RequestId: 45396de3-dda5-4ab9-9774-65d0b4a9a22b
REPORT RequestId: 45396de3-dda5-4ab9-9774-65d0b4a9a22b	Init Duration: 56.35 ms	Duration: 6901.78 ms	Billed Duration: 7000 ms 	Memory Size: 1024 MB	Max Memory Used: 427 MB	
RequestId: 45396de3-dda5-4ab9-9774-65d0b4a9a22b Error: Runtime exited with error: signal: segmentation fault (core dumped)
Runtime.ExitError
```

I don't know why

This my code
https://github.com/ifew/aws-lambda-lambdanative-db-dapper/blob/master/src/aws-lambda-lambdanative-db-dapper/Function.cs

**Comment by zaccharles** [comment]
Perhaps try compiling a simple console app that uses Dapper with CoreRT. It's quite possible that it uses a something that isn't supported by CoreRT yet. I don't think it would be LambdaNative causing this problem.

If you find it doesn't work under CoreRT, you could raise an issue with [them](https://github.com/dotnet/corert). They're usually quite helpful.

**Comment by ifew** [comment]
> Perhaps try compiling a simple console app that uses Dapper with CoreRT. It's quite possible that it uses a something that isn't supported by CoreRT yet. I don't think it would be LambdaNative causing this problem.
> 
> If you find it doesn't work under CoreRT, you could raise an issue with [them](https://github.com/dotnet/corert). They're usually quite helpful.

OK, I develop example [ifew/corert-db-dapper](https://github.com/ifew/corert-db-dapper) and it's work.

**Comment by zaccharles** [comment]
Your example doesn't have the `Microsoft.DotNet.ILCompiler` package so it can't be building with CoreRT. It looks like it will just be building with .NET Core

**Comment by ifew** [comment]
@zaccharles OK, after I added ```Microsoft.DotNet.ILCompiler``` its fail, I think from reflection. and  I will ask from Corert Issues Board

but you have any ideas for getting a list of runtime directive? 

Thank you

**Comment by ifew** [comment]
@zaccharles OK, I found the root cause from CoreRT has not to support some ORM. and now I have completed with ADO.NET at https://github.com/ifew/aws-lambda-lambdanative-db

Thank you for support
