### ISSUE TITLE
Connect to Azure MS SQL

### ISSUE THREAD

**Issue by vasilijgla** [zaccharles/lambda-native#5]
As I've mentioned [here](https://github.com/zaccharles/lambda-native/issues/3) you can't use standard  System.Data.SqlClient in lambda-native... But solution with [MySqlConnector](https://github.com/ifew/aws-lambda-lambdanative-db)  is useless  for me due to the fact that I use Azure MS SQL Server, not MYSQL...
And how do i can connect to Azure MS SQL server?

**Comment by zaccharles** [comment]
Hi @vasilijgla, the simple answer is that you need to find or build libraries that are supported by CoreRT.  Unfortunately, there's no list of libraries and I don't have the bandwidth to help on issues like this that aren't directly related to Lambda Native. Sorry about that, good luck!
